"""AutoNovel 例外モジュール。

基底例外および各フェーズ（Phase 3 等）の例外を一元的に提供する。
"""

from __future__ import annotations

from .base import (
    APIError,
    AppError,
    EngineError,
    HegemonyError,
    LLMAuthenticationError,
    LLMContentFilterError,
    LLMError,
    LLMInvalidRequestError,
    LLMRateLimitError,
    LLMServerError,
    LLMTemporaryError,
    LLMTimeoutError,
    LLMTokenLimitError,
    LLMUnknownError,
    LLMUnrecoverableError,
    LLMValidationError,
    NotFoundError,
    PipelineError,
    ValidationError,
)
from .phase3 import (
    CompressionCacheError,
    CompressionConfigError,
    CompressionError,
    CompressionLayerError,
    CompressionModelError,
    ConfigurationError,
    DAGCycleError,
    DAGResourceError,
    DAGSchedulerError,
    DAGTaskError,
    DAGTimeoutError,
    DAGValidationError,
    Phase3Error,
    ResourceExhaustedError,
    SocialGenerationError,
    SocialGraphError,
    SocialInteractionError,
    SocialSimulationError,
)

__all__ = [
    # 基底・共通例外
    "HegemonyError",
    "EngineError",
    "LLMError",
    "LLMTemporaryError",
    "LLMTokenLimitError",
    "LLMValidationError",
    "LLMUnrecoverableError",
    "APIError",
    "AppError",
    "ValidationError",
    "NotFoundError",
    "PipelineError",
    "LLMAuthenticationError",
    "LLMContentFilterError",
    "LLMInvalidRequestError",
    "LLMRateLimitError",
    "LLMServerError",
    "LLMTimeoutError",
    "LLMUnknownError",
    # Phase 3 例外
    "Phase3Error",
    "CompressionError",
    "CompressionConfigError",
    "CompressionModelError",
    "CompressionCacheError",
    "CompressionLayerError",
    "DAGSchedulerError",
    "DAGValidationError",
    "DAGCycleError",
    "DAGResourceError",
    "DAGTaskError",
    "DAGTimeoutError",
    "SocialInteractionError",
    "SocialGenerationError",
    "SocialGraphError",
    "SocialSimulationError",
    "ConfigurationError",
    "ResourceExhaustedError",
]