[alembic]
# Specify the directory where your migration environment (e.g., env.py) is located.
script_location = src/backend/alembic
sqlalchemy.url = sqlite:///kaku_hegemony_v2.db

[loggers]
keys = root,sqlalchemy,alembic,uvicorn,uvicorn.error

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[logger_uvicorn]
level = INFO
handlers = console
qualname = uvicorn

[logger_uvicorn.error]
level = INFO
handlers = console
qualname = uvicorn.error

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S