import logging
import os
import time

from google import genai
from google.genai import types

from config.imagen_models import get_imagen_model_id
from src.models.illustration import SafetyLevel

logger = logging.getLogger(__name__)


class ImageService:
    """Google GenAI Imagen API 連携サービス。

    デフォルトは fast tier を使用し、表紙・挿絵・キャラクターイラストの
    生成を担う。モデルIDは config.imagen_models を介して解決する。
    """

    def __init__(
        self,
        api_key: str,
        storage_dir: str = "static/illustrations",
        default_model: str = "fast",
    ):
        if not api_key:
            raise ValueError(
                "ImageService requires a non-empty api_key. "
                "Set GOOGLE_GENAI_API_KEY or pass api_key explicitly."
            )
        self.client = genai.Client(api_key=api_key)
        self.storage_dir = storage_dir
        self.default_model = get_imagen_model_id(default_model)

    async def generate(
        self,
        prompt: str,
        model: str | None = None,
        aspect_ratio: str = "3:4",
        negative_prompt: str = "",
        safety_level: SafetyLevel = SafetyLevel.BLOCK_SOME,
        number_of_images: int = 1,
    ) -> str:
        """Imagenモデルを使用して画像を生成し、保存してURLを返す。"""
        model = get_imagen_model_id(model or self.default_model)
        start = time.time()
        try:
            safety_settings = self._build_safety_settings(safety_level)

            config_kwargs: dict = {
                "number_of_images": number_of_images,
                "safety_settings": safety_settings,
                "aspect_ratio": aspect_ratio,
            }
            if negative_prompt:
                config_kwargs["negative_prompt"] = negative_prompt

            config = types.GenerateImagesConfig(**config_kwargs)

            response = self.client.models.generate_images(
                model=model,
                prompt=prompt,
                config=config,
            )

            if not response.generated_images:
                raise RuntimeError("No images were generated by the model.")

            image = response.generated_images[0]
            image_bytes = image.image.image_bytes

            image_url = self._save_image(image_bytes)

            elapsed = int((time.time() - start) * 1000)
            logger.info(f"Image generated in {elapsed}ms -> {image_url}")
            return image_url

        except Exception as e:
            logger.error(f"Image generation failed: {str(e)}")
            raise e

    def _build_safety_settings(self, level: SafetyLevel):
        """SafetyLevel を GenAI SDK の SafetySetting リストに変換する。"""
        threshold_map = {
            SafetyLevel.BLOCK_MOST.value: "BLOCK_MOST",
            SafetyLevel.BLOCK_SOME.value: "BLOCK_SOME",
            SafetyLevel.BLOCK_FEW.value: "BLOCK_FEW",
            SafetyLevel.R15_CONTENT.value: "BLOCK_MOST",  # R15は露骨な表現を強く遮断
        }
        threshold = threshold_map.get(getattr(level, "value", level), "BLOCK_SOME")
        return [
            types.SafetySetting(
                category="HARM_CATEGORY_SEXUALLY_EXPLICIT",
                threshold=threshold,
            )
        ]

    def _save_image(self, image_bytes: bytes) -> str:
        """画像をファイルシステムに保存し、相対パスを返す。"""
        save_dir = self.storage_dir
        os.makedirs(save_dir, exist_ok=True)

        filename = f"img_{int(time.time() * 1000)}.png"
        filepath = os.path.join(save_dir, filename)

        with open(filepath, "wb") as f:
            f.write(image_bytes)

        return f"/{filepath}"
