import os
import time
import logging
from typing import Optional, Dict, Any
from google import genai
from google.genai import types
from src.models.illustration import IllustrationRequest, IllustrationResult, SafetyLevel

logger = logging.getLogger(__name__)

class ImageService:
    """Google GenAI Imagen API 連携サービス"""
    
    def __init__(self, api_key: str):
        self.client = genai.Client(api_key=api_key)

    async def generate(
        self, 
        prompt: str, 
        model: str = "imagen-4.0-generate-001", 
        safety_level: SafetyLevel = SafetyLevel.BLOCK_SOME
    ) -> str:
        """
        Imagenモデルを使用して画像を生成し、保存してURLを返す
        """
        try:
            # 安全設定の変換
            safety_settings = self._map_safety_level(safety_level)
            
            # 画像生成リクエスト
            response = self.client.models.generate_images(
                model=model,
                prompt=prompt,
                config=types.GenerateImagesConfig(
                    number_of_images=1,
                    safety_settings=safety_settings,
                    # 他のパラメータ（アスペクト比など）は必要に応じて追加
                )
            )
            
            if not response.generated_images:
                raise RuntimeError("No images were generated by the model.")

            # 生成された画像データを取得
            image = response.generated_images[0]
            image_bytes = image.image.image_bytes
            
            # 画像の保存処理
            image_url = self._save_image(image_bytes)
            
            return image_url

        except Exception as e:
            logger.error(f"Image generation failed: {str(e)}")
            raise e

    def _map_safety_level(self, level: SafetyLevel) -> Dict[str, Any]:
        """内部的なSafetyLevelをGenAI APIの形式に変換"""
        # 注: 実際の実装ではGoogle GenAI SDKの正確な型定義に合わせる必要があります
        mapping = {
            SafetyLevel.BLOCK_MOST: "BLOCK_MOST",
            SafetyLevel.BLOCK_SOME: "BLOCK_SOME",
            SafetyLevel.BLOCK_FEW: "BLOCK_FEW",
            SafetyLevel.R15_CONTENT: "BLOCK_SOME", # R15はBLOCK_SOME程度で調整
        }
        return {"safety_settings": [{"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": mapping.get(level, "BLOCK_SOME")}]}

    def _save_image(self, image_bytes: bytes) -> str:
        """画像をファイルシステムに保存し、相対パスを返す"""
        # 保存ディレクトリの作成
        save_dir = "static/illustrations"
        os.makedirs(save_dir, exist_ok=True)
        
        filename = f"img_{int(time.time()*1000)}.png"
        filepath = os.path.join(save_dir, filename)
        
        with open(filepath, "wb") as f:
            f.write(image_bytes)
            
        return f"/{filepath}"
