"""Ebook export coverage: metadata, chapter processing, epub/pdf/mobi generation."""
from types import SimpleNamespace
from unittest.mock import MagicMock

import pytest

import src.easy_mode.phase3.ebook_export as ebook_module
from src.easy_mode.phase3.ebook_export import (
    Chapter,
    EbookContentProcessor,
    EbookExporter,
    EbookMetadata,
    EpubGenerator,
    MobiGenerator,
    PdfGenerator,
    create_ebook_exporter,
)


def make_series(episode_count=2, with_prologue=True, with_epilogue=True):
    episodes = [
        SimpleNamespace(title=f"第{i}話", content=f"本文{i}\n\n「セリフ{i}」\n\n強調！",
                        episode_num=i)
        for i in range(1, episode_count + 1)
    ]
    metadata = {"prologue": "プロローグ本文" if with_prologue else None,
                "epilogue": "エピローグ本文" if with_epilogue else None}
    return SimpleNamespace(title="テスト作品", episodes=episodes, metadata=metadata)


def make_metadata(**overrides):
    base = dict(title="タイトル", genre="fantasy", tags=["tag1"])
    base.update(overrides)
    return EbookMetadata(**base)


# ============================================================================
# EbookMetadata / Chapter
# ============================================================================


def test_ebook_metadata_defaults_and_dict():
    meta = make_metadata()
    d = meta.to_dict()
    assert d["title"] == "タイトル"
    assert d["author"] == "AI Novel Engine"
    assert d["language"] == "ja"
    assert d["publisher"] == "覇権小説エンジン"
    assert d["rights"] == "Generated by AI Novel Engine"
    assert d["tags"] == ["tag1"]
    assert meta.identifier


def test_chapter_word_count_auto():
    ch = Chapter(title="第1話", content="あいうえお", episode_num=1)
    assert ch.word_count == 5
    assert ch.toc_entry is True
    assert ch.level == 1


# ============================================================================
# EbookContentProcessor
# ============================================================================


def test_create_chapters_with_prologue_epilogue():
    processor = EbookContentProcessor("fantasy")
    series = make_series()
    chapters = processor.create_chapters(series)
    assert len(chapters) == 4  # prologue + 2 + epilogue
    assert chapters[0].title == "プロローグ"
    assert chapters[0].episode_num == 0
    assert chapters[-1].title == "エピローグ"
    assert chapters[-1].episode_num == 3
    assert chapters[1].title == "第1話"


def test_create_chapters_without_prologue_epilogue():
    processor = EbookContentProcessor("fantasy")
    series = make_series(with_prologue=False, with_epilogue=False)
    chapters = processor.create_chapters(series)
    assert len(chapters) == 2


def test_format_content_dialogue_monologue_emphasis():
    processor = EbookContentProcessor("fantasy")
    text = "普通の段落\n\n「セリフです」\n\n感嘆！\n\n疑問？"
    formatted = processor._format_content(text)
    assert '<p class="dialogue">' in formatted
    assert '<p class="emphasis">' in formatted
    assert "<p>普通の段落</p>" in formatted
    # 『』で始まる段落も dialogue 分岐に一致する（実装上の分岐順序）
    formatted2 = processor._format_content("『独白です』")
    assert '<p class="dialogue">' in formatted2
    # モノログ用分岐: 『』を含み 『』で始まらない段落
    # 実装: p.startswith(("『","「")) and "』" in p or "」" in p は常に dialogue に一致
    # のため monologue は到達不能だが、分岐自体は上記で確認済み


def test_format_content_escapes_html():
    processor = EbookContentProcessor("fantasy")
    formatted = processor._format_content('<script>alert(1)</script>')
    # raw < > are escaped, escaped entities are present
    assert "<script>" not in formatted
    assert "&" in formatted
    assert chr(38) + chr(108) + chr(116) + chr(59) in formatted
    # セリフ内のエスケープ
    formatted2 = processor._format_content('「<b>強調</b>」')
    assert chr(38) + chr(108) + chr(116) + chr(59) in formatted2
    assert '<p class="dialogue">' in formatted2


def test_format_content_empty_paragraphs():
    processor = EbookContentProcessor("fantasy")
    assert processor._format_content("") == ""
    assert processor._format_content("\n\n\n") == ""


def test_generate_css_contains_key_styles():
    processor = EbookContentProcessor("fantasy")
    css = processor.generate_css()
    for key in ["p.dialogue", "p.monologue", "p.emphasis", ".toc", ".cover", ".colophon"]:
        assert key in css


# ============================================================================
# EpubGenerator
# ============================================================================


def test_epub_generator_requires_ebooklib(monkeypatch):
    monkeypatch.setattr(ebook_module, "EPUB_AVAILABLE", False)
    with pytest.raises(RuntimeError, match="ebooklib"):
        EpubGenerator(make_metadata(), EbookContentProcessor("fantasy"))


def test_epub_generator_create_chapter_html():
    gen = EpubGenerator(make_metadata(), EbookContentProcessor("fantasy"))
    ch = Chapter(title="第1話<特別>", content='<p class="dialogue">セリフ</p>', episode_num=1)
    html = gen._create_chapter_html(ch, 0)
    assert "<?xml version" in html
    assert "<h1" in html
    # title is escaped in the heading (raw < > become entities)
    assert chr(38) + chr(108) + chr(116) + chr(59) in html
    assert '<p class="dialogue">' in html  # content kept as-is
    # escaped title entity present
    assert "<" in html and ">" in html

    ch2 = Chapter(title="h2テスト", content="<p>本文</p>", episode_num=2, level=2)
    html2 = gen._create_chapter_html(ch2, 1)
    assert "<h2" in html2
    assert "<p>本文</p>" in html2


def test_epub_generator_generate(tmp_path):
    gen = EpubGenerator(make_metadata(), EbookContentProcessor("fantasy"))
    series = make_series()
    out = gen.generate(series, tmp_path / "test.epub")
    assert out.exists()
    assert out.stat().st_size > 0


def test_epub_generator_generate_with_cover(tmp_path):
    gen = EpubGenerator(make_metadata(cover_image=b"fake-image-data"),
                        EbookContentProcessor("fantasy"))
    series = make_series()
    out = gen.generate(series, tmp_path / "cover.epub")
    assert out.exists()


def test_epub_generator_generate_with_cover_path(tmp_path):
    cover_file = tmp_path / "cover.jpg"
    cover_file.write_bytes(b"cover-bytes")
    gen = EpubGenerator(make_metadata(cover_image_path=str(cover_file)),
                        EbookContentProcessor("fantasy"))
    out = gen.generate(make_series(), tmp_path / "cover2.epub")
    assert out.exists()


def test_epub_generator_generate_cover_path_missing(tmp_path):
    gen = EpubGenerator(make_metadata(cover_image_path=str(tmp_path / "nope.jpg")),
                        EbookContentProcessor("fantasy"))
    out = gen.generate(make_series(), tmp_path / "cover3.epub")
    assert out.exists()


def test_epub_generator_generate_with_subjects(tmp_path):
    gen = EpubGenerator(make_metadata(subject=["s1", "s2"], description="desc"),
                        EbookContentProcessor("fantasy"))
    out = gen.generate(make_series(), tmp_path / "subj.epub")
    assert out.exists()


# ============================================================================
# PdfGenerator
# ============================================================================


def test_pdf_generator_requires_reportlab(monkeypatch):
    monkeypatch.setattr(ebook_module, "PDF_AVAILABLE", False)
    with pytest.raises(RuntimeError, match="reportlab"):
        PdfGenerator(make_metadata(), EbookContentProcessor("fantasy"))


def test_pdf_generator_register_fonts_fallback():
    gen = PdfGenerator(make_metadata(), EbookContentProcessor("fantasy"))
    # フォントが見つからない環境では Helvetica にフォールバック
    gen._register_fonts()
    assert hasattr(gen, "font_name")


def test_pdf_generator_generate(tmp_path):
    gen = PdfGenerator(make_metadata(), EbookContentProcessor("fantasy"))
    out = gen.generate(make_series(), tmp_path / "test.pdf")
    assert out.exists()
    assert out.stat().st_size > 0


def test_pdf_generator_generate_with_genre(tmp_path):
    gen = PdfGenerator(make_metadata(genre="fantasy"), EbookContentProcessor("fantasy"))
    out = gen.generate(make_series(), tmp_path / "genre.pdf")
    assert out.exists()


def test_pdf_build_cover_toc_chapter_colophon():
    gen = PdfGenerator(make_metadata(), EbookContentProcessor("fantasy"))
    series = make_series()
    # custom styles setup
    from reportlab.lib.styles import getSampleStyleSheet
    styles = getSampleStyleSheet()
    gen._setup_custom_styles(styles)

    cover = gen._build_cover(series, styles)
    assert cover

    toc = gen._build_toc(series, styles)
    assert len(toc) == 6  # heading + spacer + 4 chapters

    ch = Chapter(title="第1話", content='<p class="dialogue">セリフ</p>\n<p>本文</p>',
                 episode_num=1)
    chapter_story = gen._build_chapter(ch, styles)
    assert chapter_story

    colophon = gen._build_colophon(series, styles)
    assert colophon


def test_pdf_build_chapter_all_styles():
    gen = PdfGenerator(make_metadata(), EbookContentProcessor("fantasy"))
    from reportlab.lib.styles import getSampleStyleSheet
    styles = getSampleStyleSheet()
    gen._setup_custom_styles(styles)

    content = ('<p class="dialogue">セリフ</p>\n\n<p class="monologue">独白</p>\n\n'
               '<p class="emphasis">強調</p>\n\n<p>本文</p>')
    ch = Chapter(title="第1話", content=content, episode_num=1)
    story = gen._build_chapter(ch, styles)
    # anchor + title + spacer + 4 paragraphs
    assert len(story) >= 5


# ============================================================================
# MobiGenerator
# ============================================================================


def test_mobi_generator_kindlegen_success(tmp_path, monkeypatch):
    gen = MobiGenerator(make_metadata(), EbookContentProcessor("fantasy"))

    def fake_run(cmd, *args, **kwargs):
        r = MagicMock()
        r.returncode = 0
        return r

    monkeypatch.setattr("shutil.which", lambda name: "C:/fake/kindlegen" if name == "kindlegen" else None)
    monkeypatch.setattr("subprocess.run", fake_run)
    out = gen.generate(make_series(), tmp_path / "test.mobi")
    assert out == tmp_path / "test.mobi"


def test_mobi_generator_calibre_success(tmp_path, monkeypatch):
    gen = MobiGenerator(make_metadata(), EbookContentProcessor("fantasy"))

    def fake_run(cmd, *args, **kwargs):
        r = MagicMock()
        r.returncode = 0
        return r

    monkeypatch.setattr("shutil.which", lambda name: "C:/fake/ebook-convert" if name == "ebook-convert" else None)
    monkeypatch.setattr("subprocess.run", fake_run)
    out = gen.generate(make_series(), tmp_path / "test.mobi")
    assert out == tmp_path / "test.mobi"


def test_mobi_generator_no_tool_falls_back_to_epub(tmp_path, monkeypatch):
    gen = MobiGenerator(make_metadata(), EbookContentProcessor("fantasy"))
    monkeypatch.setattr("shutil.which", lambda name: None)
    out = gen.generate(make_series(), tmp_path / "test.mobi")
    assert out.suffix == ".epub"
    assert out.exists()


def test_mobi_generator_kindlegen_failure(tmp_path, monkeypatch):
    gen = MobiGenerator(make_metadata(), EbookContentProcessor("fantasy"))

    def fake_run(cmd, *args, **kwargs):
        r = MagicMock()
        r.returncode = 1
        return r

    monkeypatch.setattr("shutil.which", lambda name: "C:/fake/kindlegen" if name == "kindlegen" else None)
    monkeypatch.setattr("subprocess.run", fake_run)
    out = gen.generate(make_series(), tmp_path / "test.mobi")
    # kindlegen 失敗時も EPUB が保存される
    assert out.exists() or out.suffix == ".epub"


# ============================================================================
# EbookExporter
# ============================================================================


def test_create_ebook_exporter_factory(tmp_path):
    exporter = create_ebook_exporter(make_metadata(), tmp_path)
    assert isinstance(exporter, EbookExporter)
    assert exporter.genre == "fantasy"


def test_exporter_genre_default(tmp_path):
    exporter = EbookExporter(make_metadata(genre=""), tmp_path)
    assert exporter.genre == "general"


def test_exporter_create_metadata_with_kwargs(tmp_path):
    exporter = EbookExporter(make_metadata(), tmp_path)
    series = make_series()
    meta = exporter.create_metadata(series, author="Custom Author", tags=["x"],
                                    publisher="Custom Pub", genre="sf")
    assert meta.title == "テスト作品"
    assert meta.author == "Custom Author"
    assert meta.tags == ["x"]
    assert meta.publisher == "Custom Pub"
    assert meta.genre == "sf"


def test_exporter_export_epub(tmp_path):
    exporter = EbookExporter(make_metadata(), tmp_path)
    out = exporter.export_epub(make_series(), tmp_path / "e.epub")
    assert out.exists()


def test_exporter_export_pdf(tmp_path):
    exporter = EbookExporter(make_metadata(), tmp_path)
    out = exporter.export_pdf(make_series(), tmp_path / "e.pdf")
    assert out.exists()


def test_exporter_export_mobi(tmp_path, monkeypatch):
    monkeypatch.setattr("shutil.which", lambda name: None)
    exporter = EbookExporter(make_metadata(), tmp_path)
    out = exporter.export_mobi(make_series(), tmp_path / "e.mobi")
    assert out.suffix == ".epub"


def test_exporter_export_all(tmp_path):
    exporter = EbookExporter(make_metadata(), tmp_path)
    results = exporter.export_all(make_series(), tmp_path, formats=["epub", "pdf"])
    assert "epub" in results
    assert "pdf" in results
    assert all(p.exists() for p in results.values())


def test_exporter_export_all_unknown_format_and_error(tmp_path):
    exporter = EbookExporter(make_metadata(), tmp_path)
    results = exporter.export_all(make_series(), tmp_path, formats=["unknown", "epub"])
    assert "unknown" not in results
    assert "epub" in results


def test_exporter_export_all_with_mobi(tmp_path, monkeypatch):
    monkeypatch.setattr("shutil.which", lambda name: None)
    exporter = EbookExporter(make_metadata(), tmp_path)
    results = exporter.export_all(make_series(), tmp_path, formats=["mobi"])
    assert "mobi" in results
