# Centralized constants - to be implemented

# HTTPタイムアウト設定（秒）
DEFAULT_TIMEOUT_SEC = 30.0
LONG_RUNNING_TIMEOUT_SEC = 300.0  # 5分


# レート制限設定
RATE_LIMIT_MAX_REQUESTS = 100
RATE_LIMIT_WINDOW_SECONDS = 60
RATE_LIMIT_STORE_MAX_ENTRIES = 10000


# 長時間実行タスク用タイムアウト（config.constantsから移行）
LONG_RUNNING_TIMEOUT_SEC = 300.0


# リトライ・再試行設定
DEFAULT_MAX_RETRIES = 3
MAX_RETRY_DELAY_SEC = 30.0

# 閾値・スコア設定
INTEREST_THRESHOLD_LOW = 60
INTEREST_THRESHOLD_MEDIUM = 70
INTEREST_THRESHOLD_HIGH = 75
INTEREST_THRESHOLD_VERY_HIGH = 80
INTEREST_THRESHOLD_CRITICAL = 85
INTEREST_THRESHOLD_EXCELLENT = 90
INTEGRITY_THRESHOLD = 70

# バッチ・並列処理設定
DEFAULT_BATCH_SIZE = 100
MAX_PARALLEL_AUDITS = 3
MAX_WORKERS = 1
MAX_REWRITE_ITERATIONS = 3

# キャッシュ設定
DEFAULT_CACHE_TTL_SEC = 300
MAX_EMBEDDING_CACHE_SIZE = 1000

# 文字数・長さ制限
MAX_CHAPTER_CHARS = 3000
MAX_LINE_CHARS_DENSE = 35
MAX_LINE_CHARS_NORMAL = 45
MAX_KEY_PHRASE_LEN = 20

# タイムアウト設定（追加）
SSE_TIMEOUT_SEC = 15.0
REDIS_CONNECT_TIMEOUT_SEC = 2.0
REDIS_SOCKET_TIMEOUT_SEC = 1.0
DB_BUSY_TIMEOUT_MS = 30000

# 履歴・制限
MAX_HISTORY = 10
MAX_PROMPT_VERSIONS_DEFAULT = 100
MAX_PROMPT_VERSIONS_SMALL = 20

# DB設定
DB_POOL_MAX_OVERFLOW = 20
DB_CACHE_SIZE_KB = 64000


# 追加のリトライ・品質設定
DEFAULT_RETRY_DELAY_SEC = 1.0
RETRY_BACKOFF_FACTOR = 2.0
QUALITY_THRESHOLD_EARLY_EXIT = 0.95

