"""
電子書籍エクスポート
小説をEPUB・MOBI・PDF形式で出力
"""

from __future__ import annotations

import importlib.util
import logging
import re
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from src.easy_mode.pipeline import SeriesResult

logger = logging.getLogger(__name__)


# オプショナル依存チェック
EPUB_AVAILABLE = importlib.util.find_spec("ebooklib") is not None
if not EPUB_AVAILABLE:
    logger.warning("ebooklib not available. EPUB export will be limited.")

PDF_AVAILABLE = importlib.util.find_spec("reportlab") is not None
if not PDF_AVAILABLE:
    logger.warning("reportlab not available. PDF export will be limited.")


@dataclass
class EbookMetadata:
    """電子書籍メタデータ"""

    title: str
    author: str = "AI Novel Engine"
    language: str = "ja"
    publisher: str = "覇権小説エンジン"
    publication_date: str = field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d"))
    identifier: str = field(default_factory=lambda: str(uuid.uuid4()))
    description: str = ""
    subject: List[str] = field(default_factory=list)
    cover_image: Optional[bytes] = None
    cover_image_path: Optional[str] = None
    rights: str = "Generated by AI Novel Engine"
    genre: str = ""
    tags: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "title": self.title,
            "author": self.author,
            "language": self.language,
            "publisher": self.publisher,
            "publication_date": self.publication_date,
            "identifier": self.identifier,
            "description": self.description,
            "subject": self.subject,
            "rights": self.rights,
            "genre": self.genre,
            "tags": self.tags,
        }


@dataclass
class Chapter:
    """チャプター（電子書籍用）"""

    title: str
    content: str
    episode_num: int
    word_count: int = 0
    toc_entry: bool = True
    level: int = 1  # 見出しレベル

    def __post_init__(self):
        self.word_count = len(self.content)


class EbookContentProcessor:
    """電子書籍用コンテンツ処理"""

    def __init__(self, genre: str):
        self.genre = genre

    def create_chapters(self, series: SeriesResult) -> List[Chapter]:
        """シリーズからチャプター作成"""
        chapters = []

        # プロローグ
        if series.metadata.get("prologue"):
            chapters.append(
                Chapter(
                    title="プロローグ",
                    content=self._format_content(series.metadata["prologue"]),
                    episode_num=0,
                    level=1,
                )
            )

        # 各話
        for episode in series.episodes:
            title = episode.title
            content = self._format_content(episode.content)
            chapters.append(
                Chapter(title=title, content=content, episode_num=episode.episode_num, level=1)
            )

        # エピローグ
        if series.metadata.get("epilogue"):
            chapters.append(
                Chapter(
                    title="エピローグ",
                    content=self._format_content(series.metadata["epilogue"]),
                    episode_num=len(series.episodes) + 1,
                    level=1,
                )
            )

        return chapters

    def _format_content(self, text: str) -> str:
        """HTML用に整形"""
        # 段落分割
        paragraphs = re.split(r"\n\s*\n", text)

        formatted = []
        for p in paragraphs:
            p = p.strip()
            if not p:
                continue

            # セリフ検出
            if p.startswith(("「", "『", '"')):
                formatted.append(f'<p class="dialogue">{self._escape_html(p)}</p>')
            # 思考・独白
            elif p.startswith(("『", "「")) and "』" in p or "」" in p:
                formatted.append(f'<p class="monologue">{self._escape_html(p)}</p>')
            # 強調
            elif "！" in p or "？" in p:
                formatted.append(f'<p class="emphasis">{self._escape_html(p)}</p>')
            else:
                formatted.append(f"<p>{self._escape_html(p)}</p>")

        return "\n".join(formatted)

    def _escape_html(self, text: str) -> str:
        """HTMLエスケープ"""
        return (
            text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&#39;")
        )

    def generate_css(self) -> str:
        """共通CSS生成"""
        return """
/* 共通スタイル */
body { 
    font-family: "Noto Serif JP", "Hiragino Mincho ProN", serif; 
    line-height: 1.8; 
    margin: 0; 
    padding: 1em;
    color: #333;
}

h1, h2, h3 { 
    font-family: "Noto Sans JP", "Hiragino Kaku Gothic ProN", sans-serif;
    font-weight: bold;
    margin-top: 2em;
    margin-bottom: 1em;
    color: #1a1a1a;
}

h1 { font-size: 1.8em; border-bottom: 2px solid #333; padding-bottom: 0.3em; }
h2 { font-size: 1.5em; }
h3 { font-size: 1.3em; }

p { 
    text-indent: 1em; 
    margin: 0.5em 0;
    text-align: justify;
}

p:first-of-type { text-indent: 0; }

/* セリフ */
p.dialogue { 
    text-indent: 0; 
    margin: 0.5em 1em;
    font-style: normal;
}

/* 独白 */
p.monologue { 
    text-indent: 0; 
    margin: 0.5em 1.5em;
    font-style: italic;
    color: #555;
}

/* 強調 */
p.emphasis { 
    font-weight: bold; 
}

/* ルビ */
ruby { ruby-align: center; }
rt { font-size: 0.6em; }

/* ページ区切り */
.page-break { page-break-before: always; }

/* 目次 */
.toc { margin: 2em 0; }
.toc a { text-decoration: none; color: #333; }
.toc a:hover { text-decoration: underline; }

/* 表紙 */
.cover { text-align: center; margin: 4em 0; page-break-after: always; }
.cover img { max-width: 80%; height: auto; }
.cover-title { font-size: 2.5em; margin-top: 1em; }
.cover-author { font-size: 1.2em; margin-top: 0.5em; color: #666; }

/* コルフォン */
.colophon { 
    margin-top: 4em; 
    padding-top: 1em; 
    border-top: 1px solid #ccc; 
    font-size: 0.8em; 
    color: #666; 
    text-align: center;
}
"""


class EpubGenerator:
    """EPUB生成器"""

    def __init__(self, metadata: EbookMetadata, processor: EbookContentProcessor):
        self.metadata = metadata
        self.processor = processor

        if not EPUB_AVAILABLE:
            raise RuntimeError(
                "ebooklib is required for EPUB generation. Install with: pip install ebooklib"
            )

    def generate(self, series: SeriesResult, output_path: Path) -> Path:
        """EPUB生成"""
        book = epub.EpubBook()

        # メタデータ設定
        book.set_identifier(self.metadata.identifier)
        book.set_title(self.metadata.title)
        book.set_language(self.metadata.language)
        book.add_author(self.metadata.author)
        book.add_metadata("DC", "publisher", self.metadata.publisher)
        book.add_metadata("DC", "date", self.metadata.publication_date)
        book.add_metadata("DC", "description", self.metadata.description)
        book.add_metadata("DC", "rights", self.metadata.rights)

        for subject in self.metadata.subject:
            book.add_metadata("DC", "subject", subject)

        # カバー画像
        if self.metadata.cover_image:
            book.set_cover("cover.jpg", self.metadata.cover_image)
        elif self.metadata.cover_image_path:
            cover_path = Path(self.metadata.cover_image_path)
            if cover_path.exists():
                book.set_cover("cover.jpg", cover_path.read_bytes())

        # CSS
        style = self.processor.generate_css()
        nav_css = epub.EpubItem(
            uid="style_nav",
            file_name="style/nav.css",
            media_type="text/css",
            content=style.encode("utf-8"),
        )
        book.add_item(nav_css)

        # チャプター作成
        chapters = self.processor.create_chapters(series)
        epub_chapters = []

        for i, chapter in enumerate(chapters):
            # HTML生成
            html_content = self._create_chapter_html(chapter, i)

            epub_chapter = epub.EpubHtml(
                title=chapter.title, file_name=f"chap_{i + 1:03d}.xhtml", lang="ja"
            )
            epub_chapter.content = html_content.encode("utf-8")
            epub_chapter.add_item(nav_css)

            book.add_item(epub_chapter)
            epub_chapters.append(epub_chapter)

        # 目次
        book.toc = [(epub.Section(ch.title), [c]) for ch, c in zip(chapters, epub_chapters)]

        # ナビゲーション
        book.add_item(epub.EpubNcx())
        book.add_item(epub.EpubNav())

        # スパイン（読み順）
        book.spine = ["nav"] + epub_chapters

        # 保存
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        epub.write_epub(str(output_path), book, {})

        logger.info(f"EPUB generated: {output_path}")
        return output_path

    def _create_chapter_html(self, chapter: Chapter, index: int) -> str:
        """チャプターHTML生成"""
        level_tag = "h1" if chapter.level == 1 else "h2"

        return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="ja" xml:lang="ja">
<head>
    <meta charset="UTF-8"/>
    <title>{self._escape_html(chapter.title)}</title>
    <link rel="stylesheet" type="text/css" href="style/nav.css"/>
</head>
<body>
    <{level_tag} class="chapter-title">{self._escape_html(chapter.title)}</{level_tag}>
    {chapter.content}
</body>
</html>"""

    def _escape_html(self, text: str) -> str:
        return (
            text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&#39;")
        )


class PdfGenerator:
    """PDF生成器（reportlab使用）"""

    def __init__(self, metadata: EbookMetadata, processor: EbookContentProcessor):
        self.metadata = metadata
        self.processor = processor

        if not PDF_AVAILABLE:
            raise RuntimeError(
                "reportlab is required for PDF generation. Install with: pip install reportlab"
            )

    def generate(self, series: SeriesResult, output_path: Path) -> Path:
        """PDF生成"""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # フォント登録（日本語対応）
        self._register_fonts()

        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=A4,
            rightMargin=20 * mm,
            leftMargin=20 * mm,
            topMargin=25 * mm,
            bottomMargin=25 * mm,
        )

        # スタイル定義
        styles = getSampleStyleSheet()
        self._setup_custom_styles(styles)

        # ストーリー構築
        story = []

        # 表紙
        story.extend(self._build_cover(series))
        story.append(PageBreak())

        # 目次
        story.extend(self._build_toc(series))
        story.append(PageBreak())

        # 本文
        chapters = self.processor.create_chapters(series)
        for chapter in chapters:
            story.extend(self._build_chapter(chapter, styles))
            story.append(PageBreak())

        # 奥付
        story.extend(self._build_colophon(series, styles))

        # ビルド
        doc.build(story)

        logger.info(f"PDF generated: {output_path}")
        return output_path

    def _register_fonts(self):
        """日本語フォント登録"""
        try:
            # システムフォントを試す
            import subprocess

            result = subprocess.run(["fc-list", ":lang=ja"], capture_output=True, text=True)
            if result.returncode == 0:
                for line in result.stdout.split("\n"):
                    if (
                        "noto" in line.lower()
                        or "hiragino" in line.lower()
                        or "ipafont" in line.lower()
                    ):
                        font_path = line.split(":")[0].strip()
                        if font_path:
                            pdfmetrics.registerFont(TTFont("Japanese", font_path))
                            return
        except Exception:
            pass

        # フォールバック：デフォルトフォント使用
        logger.warning("Japanese font not found, using default")

    def _setup_custom_styles(self, styles):
        """カスタムスタイル設定"""
        from reportlab.lib.colors import HexColor
        from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT

        styles.add(
            ParagraphStyle(
                "JapaneseTitle",
                parent=styles["Title"],
                fontName="Japanese",
                fontSize=24,
                leading=36,
                alignment=TA_CENTER,
                spaceAfter=12,
                textColor=HexColor("#1a1a1a"),
            )
        )

        styles.add(
            ParagraphStyle(
                "JapaneseHeading1",
                parent=styles["Heading1"],
                fontName="Japanese",
                fontSize=18,
                leading=27,
                spaceBefore=24,
                spaceAfter=12,
                textColor=HexColor("#1a1a1a"),
            )
        )

        styles.add(
            ParagraphStyle(
                "JapaneseHeading2",
                parent=styles["Heading2"],
                fontName="Japanese",
                fontSize=15,
                leading=22,
                spaceBefore=18,
                spaceAfter=10,
                textColor=HexColor("#333333"),
            )
        )

        styles.add(
            ParagraphStyle(
                "JapaneseBody",
                parent=styles["Normal"],
                fontName="Japanese",
                fontSize=11,
                leading=19,
                alignment=TA_JUSTIFY,
                firstLineIndent=12,
                spaceBefore=6,
                spaceAfter=6,
            )
        )

        styles.add(
            ParagraphStyle(
                "JapaneseDialogue",
                parent=styles["Normal"],
                fontName="Japanese",
                fontSize=11,
                leading=19,
                alignment=TA_LEFT,
                leftIndent=18,
                spaceBefore=6,
                spaceAfter=6,
            )
        )

        styles.add(
            ParagraphStyle(
                "JapaneseMonologue",
                parent=styles["Normal"],
                fontName="Japanese",
                fontSize=11,
                leading=19,
                alignment=TA_LEFT,
                leftIndent=24,
                spaceBefore=6,
                spaceAfter=6,
                fontStyle="italic",
            )
        )

    def _build_cover(self, series: SeriesResult) -> List:
        """表紙ページ構築"""
        from reportlab.lib.units import cm
        from reportlab.platypus import Paragraph, Spacer

        story = []
        story.append(Spacer(1, 5 * cm))

        # タイトル
        story.append(Paragraph(series.title, styles["JapaneseTitle"]))
        story.append(Spacer(1, 1 * cm))

        # 著者
        story.append(Paragraph(f"著者: {self.metadata.author}", styles["Normal"]))
        story.append(Spacer(1, 0.5 * cm))

        # ジャンルタグ
        genre_text = f"ジャンル: {self.metadata.genre}" if self.metadata.genre else ""
        if genre_text:
            story.append(Paragraph(genre_text, styles["Normal"]))

        story.append(Spacer(1, 3 * cm))

        # 発行情報
        story.append(
            Paragraph(
                f"発行: {self.metadata.publisher}<br/>"
                f"発行日: {self.metadata.publication_date}<br/>"
                f"{self.metadata.rights}",
                styles["Normal"],
            )
        )

        return story

    def _build_toc(self, series: SeriesResult) -> List:
        """目次構築"""
        from reportlab.platypus import Paragraph, Spacer, TableOfContents

        story = []
        story.append(Paragraph("目次", styles["JapaneseHeading1"]))
        story.append(Spacer(1, 1 * cm))

        chapters = self.processor.create_chapters(series)
        toc = TableOfContents()
        toc.levelStyles = [styles["JapaneseHeading2"], styles["JapaneseBody"]]

        # TOCエントリ手動追加
        for i, ch in enumerate(chapters):
            if ch.toc_entry:
                story.append(
                    Paragraph(f'<a href="#chap_{i}">{ch.title}</a>', styles["JapaneseBody"])
                )

        return story

    def _build_chapter(self, chapter: Chapter, styles) -> List:
        """チャプター構築"""
        from reportlab.platypus import Paragraph, Spacer

        story = []

        # アンカー
        story.append(Paragraph(f'<a name="chap_{chapter.episode_num}"/>', styles["Normal"]))

        # タイトル
        story.append(Paragraph(chapter.title, styles["JapaneseHeading1"]))
        story.append(Spacer(1, 0.5 * cm))

        # 本文
        # HTMLからParagraphへ変換
        paragraphs = chapter.content.split("\n")
        for p_html in paragraphs:
            if not p_html.strip():
                continue

            # タグ除去してテキスト抽出
            p_text = re.sub(r"<[^>]+>", "", p_html)
            p_text = p_text.strip()
            if not p_text:
                continue

            # スタイル判定
            if 'class="dialogue"' in p_html:
                story.append(Paragraph(p_text, styles["JapaneseDialogue"]))
            elif 'class="monologue"' in p_html:
                story.append(Paragraph(p_text, styles["JapaneseMonologue"]))
            elif 'class="emphasis"' in p_html:
                story.append(Paragraph(p_text, styles["JapaneseBody"]))  # 太字は別途
            else:
                story.append(Paragraph(p_text, styles["JapaneseBody"]))

        return story

    def _build_colophon(self, series: SeriesResult, styles) -> List:
        """奥付構築"""
        from reportlab.platypus import Paragraph, Spacer

        story = []
        story.append(Spacer(1, 2 * cm))
        story.append(Paragraph("奥付", styles["JapaneseHeading2"]))
        story.append(Spacer(1, 1 * cm))

        colophon_text = f"""
        書名: {series.title}<br/>
        著者: {self.metadata.author}<br/>
        発行者: {self.metadata.publisher}<br/>
        発行日: {self.metadata.publication_date}<br/>
        識別子: {self.metadata.identifier}<br/>
        <br/>
        本書はAI Novel Engineにより自動生成された作品です。<br/>
        {self.metadata.rights}
        """

        story.append(Paragraph(colophon_text, styles["JapaneseBody"]))
        return story


class MobiGenerator:
    """MOBI生成器（kindlegen/calibre経由）"""

    def __init__(self, metadata: EbookMetadata, processor: EbookContentProcessor):
        self.metadata = metadata
        self.processor = processor

    def generate(self, series: SeriesResult, output_path: Path) -> Path:
        """MOBI生成（EPUB→MOBI変換）"""
        # まずEPUB生成
        epub_path = output_path.with_suffix(".epub")
        epub_gen = EpubGenerator(self.metadata, self.processor)
        epub_gen.generate(series, epub_path)

        # kindlegenまたはebook-convertで変換
        import shutil
        import subprocess

        # kindlegenを試す
        kindlegen = shutil.which("kindlegen")
        ebook_convert = shutil.which("ebook-convert")

        if kindlegen:
            result = subprocess.run([kindlegen, str(epub_path)], capture_output=True, text=True)
            if result.returncode == 0:
                mobi_path = epub_path.with_suffix(".mobi")
                if mobi_path != output_path:
                    mobi_path.rename(output_path)
                logger.info(f"MOBI generated via kindlegen: {output_path}")
                return output_path

        elif ebook_convert:
            result = subprocess.run(
                [ebook_convert, str(epub_path), str(output_path)], capture_output=True, text=True
            )
            if result.returncode == 0:
                logger.info(f"MOBI generated via calibre: {output_path}")
                return output_path

        # 変換ツールがない場合はEPUBをコピー
        logger.warning("No MOBI conversion tool found. Saving as EPUB instead.")
        epub_path.rename(output_path.with_suffix(".epub"))
        return output_path.with_suffix(".epub")


class EbookExporter:
    """電子書籍エクスポーター統合"""

    def __init__(self, genre: str, preset: Dict[str, Any]):
        self.genre = genre
        self.preset = preset
        self.processor = EbookContentProcessor(genre)

    def create_metadata(self, series: SeriesResult, **kwargs) -> EbookMetadata:
        """メタデータ作成"""
        author = kwargs.pop("author", "AI Novel Engine")
        tags = kwargs.pop("tags", [])
        cover_image = kwargs.pop("cover_image", None)
        cover_image_path = kwargs.pop("cover_image_path", None)

        return EbookMetadata(
            title=series.title,
            author=author,
            description=series.metadata.get("concept", ""),
            subject=[self.genre, "Web小説", "AI生成"],
            genre=self.genre,
            tags=tags + [self.genre],
            cover_image=cover_image,
            cover_image_path=cover_image_path,
            **kwargs,
        )

    def export_epub(self, series: SeriesResult, output_path: Path, **kwargs) -> Path:
        """EPUB出力"""
        metadata = self.create_metadata(series, **kwargs)
        generator = EpubGenerator(metadata, self.processor)
        return generator.generate(series, output_path)

    def export_pdf(self, series: SeriesResult, output_path: Path, **kwargs) -> Path:
        """PDF出力"""
        metadata = self.create_metadata(series, **kwargs)
        generator = PdfGenerator(metadata, self.processor)
        return generator.generate(series, output_path)

    def export_mobi(self, series: SeriesResult, output_path: Path, **kwargs) -> Path:
        """MOBI出力"""
        metadata = self.create_metadata(series, **kwargs)
        generator = MobiGenerator(metadata, self.processor)
        return generator.generate(series, output_path)

    def export_all(
        self, series: SeriesResult, output_dir: Path, formats: List[str] = None, **kwargs
    ) -> Dict[str, Path]:
        """全フォーマット出力"""
        if formats is None:
            formats = ["epub", "pdf"]

        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        results = {}
        base_name = f"{series.title}_ep{len(series.episodes)}"

        for fmt in formats:
            output_path = output_dir / f"{base_name}.{fmt}"
            try:
                if fmt == "epub":
                    results[fmt] = self.export_epub(series, output_path, **kwargs)
                elif fmt == "pdf":
                    results[fmt] = self.export_pdf(series, output_path, **kwargs)
                elif fmt == "mobi":
                    results[fmt] = self.export_mobi(series, output_path, **kwargs)
                else:
                    logger.warning(f"Unknown format: {fmt}")
            except Exception as e:
                logger.error(f"Failed to export {fmt}: {e}")

        return results


def create_ebook_exporter(genre: str, preset: Dict[str, Any]) -> EbookExporter:
    """電子書籍エクスポーター作成"""
    return EbookExporter(genre, preset)
