"純愛官能（情緒重視）": {
        "plot_pattern": "slow_life",
        "cheat_scale": 2,
        "growth_curve": "最初からカンスト(無双)",
        "system_assist": 80,
        "reality_cost": 5,
        "cost_severity": 0,
        "style_key": "style_erotic_standard",
        "default_target_eps": 30,
        "default_word_count": 1500,
    },
    "背徳官能（心理葛藤重視）": {
        "plot_pattern": "reincarnation_cheat",
        "cheat_scale": 3,
        "growth_curve": "最初からカンスト(無双)",
        "system_assist": 70,
        "reality_cost": 20,
        "cost_severity": 1,
        "style_key": "style_erotic_standard",
        "default_target_eps": 35,
        "default_word_count": 2000,
    },
    "ファンタジー官能（異種族・魔法感覚）": {
        "plot_pattern": "reincarnation_cheat",
        "cheat_scale": 4,
        "growth_curve": "最初からカンスト(無双)",
        "system_assist": 80,
        "reality_cost": 10,
        "cost_severity": 0,
        "style_key": "style_fantasy_erotic", # This would need to be defined in styles.py
        "default_target_eps": 40,
        "default_word_count": 2200,
    },
    "夫婦/既婚官能（日常情緒）": {
        "plot_pattern": "slow_life",
        "cheat_scale": 2,
        "growth_curve": "最初からカンスト(無双)",
        "system_assist": 60,
        "reality_cost": 15,
        "cost_severity": 1,
        "style_key": "style_bookworm_daily",
        "default_target_eps": 35,
        "default_word_count": 1800,
    },