CHEAT_DESCRIPTIONS = {}; COST_DESCRIPTIONS = {}; VILLAIN_STRATEGIES = []; DEBUFF_PROFILES = {}; PLOT_STRUCTURES = {}; STORY_ARCHETYPES = []; ARCHETYPE_KEY_ALIASES = {}; EASY_MODE_KEYWORDS_MAP = {}; WIZARD_GENRE_OPTIONS = []; WIZARD_ARCHETYPE_LABELS = {}; EASY_GENRES = []

