# Archetype constants for the application
from enum import Enum


class CommercialRole(Enum):
    AVATAR_OF_DESIRE = "avatar_of_desire"
    HATE_MAGNET = "hate_magnet"
    STATUS_FLIP_TRIGGER = "status_flip_trigger"
    UNIQUE_VALUE_PROPOSITION = "unique_value_proposition"
    INFORMATION_HEGEMONY = "information_hegemony"
    UNCONDITIONAL_SUPPORTER = "unconditional_supporter"

CHEAT_DESCRIPTIONS = {
    "NONE": "No cheat abilities",
    "WEAK": "Minor cheat abilities",
    "MODERATE": "Moderate cheat abilities",
    "STRONG": "Strong cheat abilities",
    "OVERPOWERED": "Overpowered cheat abilities"
}

COST_DESCRIPTIONS = {
    "LOW": "Low cost",
    "MEDIUM": "Medium cost",
    "HIGH": "High cost",
    "EXTREME": "Extreme cost"
}

VILLAIN_STRATEGIES = [
    "direct_confrontation",
    "psychological_warfare",
    "resource_drain",
    "ally_corruption",
    "time_pressure"
]

DEBUFF_PROFILES = {
    "none": {"effect": 0, "duration": 0},
    "weak": {"effect": 0.1, "duration": 5},
    "moderate": {"effect": 0.3, "duration": 10},
    "strong": {"effect": 0.5, "duration": 15}
}

PLOT_STRUCTURES = {
    "hero_journey": ["departure", "initiation", "return"],
    "three_act": ["setup", "confrontation", "resolution"],
    "five_act": ["exposition", "rising_action", "climax", "falling_action", "denouement"]
}

STORY_ARCHETYPES = {
    "overcoming_the_monster": {},
    "rags_to_riches": {},
    "the_quest": {},
    "voyage_and_return": {},
    "comedy": {},
    "tragedy": {},
    "rebirth": {},
    "pure_love_erotic": {},
    "taboo_erotic": {},
    "fantasy_erotic": {},
    "married_erotic": {},
    "カスタム": {},
    "王道ざまぁ（爽快感最大）": {
        "plot_pattern":  "exile_rise",
        "cheat_scale":   5,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 90,
        "reality_cost":  20,
        "cost_severity": 1,
        "style_key":     "style_web_standard",
        "default_target_eps": 50,
        "default_word_count": 2500,
    },
    "本格戦記（泥臭い逆転）": {
        "cheat_scale":   2,
        "growth_curve":  "徐々に成長(王道)",
        "system_assist": 30,
        "reality_cost":  80,
        "cost_severity": 4,
        "style_key":     "style_military_rational",
        "default_target_eps": 80,
        "default_word_count": 3000,
    },
    "死に戻り（絶望と執念）": {
        "cheat_scale":   3,
        "growth_curve":  "条件付き最強(ピーキー)",
        "system_assist": 50,
        "reality_cost":  60,
        "cost_severity": 5,
        "style_key":     "style_psychological_loop",
        "default_target_eps": 60,
        "default_word_count": 2800,
    },
    "ほのぼの飯テロ（ストレス皆無）": {
        "plot_pattern":  "slow_life",
        "cheat_scale":   4,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 100,
        "reality_cost":  10,
        "cost_severity": 0,
        "style_key":     "style_bookworm_daily",
        "default_target_eps": 30,
        "default_word_count": 1500,
    },
    "悪役令嬢の逆転劇": {
        "plot_pattern":  "reincarnation_cheat",
        "cheat_scale":   3,
        "growth_curve":  "徐々に成長(王道)",
        "system_assist": 60,
        "reality_cost":  40,
        "cost_severity": 2,
        "style_key":     "style_villainess_elegant",
        "default_target_eps": 40,
        "default_word_count": 2000,
    },
    "勘違い爆走（ギャップ萌え）": {
        "plot_pattern":  "reincarnation_cheat",
        "cheat_scale":   4,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 80,
        "reality_cost":  20,
        "cost_severity": 0,
        "style_key":     "style_overlord",
        "default_target_eps": 45,
        "default_word_count": 2200,
    },
    "最強テイマー（もふもふ無双）": {
        "plot_pattern":  "slow_life",
        "cheat_scale":   4,
        "growth_curve":  "徐々に成長(王道)",
        "system_assist": 70,
        "reality_cost":  10,
        "cost_severity": 1,
        "style_key":     "style_bookworm_daily",
        "default_target_eps": 35,
        "default_word_count": 1800,
    },
    "万能錬金術師（商会成り上がり）": {
        "plot_pattern":  "exile_rise",
        "cheat_scale":   3,
        "growth_curve":  "徐々に成長(王道)",
        "system_assist": 60,
        "reality_cost":  30,
        "cost_severity": 1,
        "style_key":     "style_web_standard",
        "default_target_eps": 55,
        "default_word_count": 2600,
    },
    "現代知識チート（文明無双）": {
        "plot_pattern":  "reincarnation_cheat",
        "cheat_scale":   3,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 50,
        "reality_cost":  40,
        "cost_severity": 0,
        "style_key":     "style_web_standard",
        "default_target_eps": 60,
        "default_word_count": 2700,
    },
    "絶品料理人（美食無双）": {
        "plot_pattern":  "slow_life",
        "cheat_scale":   4,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 80,
        "reality_cost":  10,
        "cost_severity": 0,
        "style_key":     "style_bookworm_daily",
        "default_target_eps": 30,
        "default_word_count": 1600,
    },
    "爆笑冒険譚（コメディ最大）": {
        "plot_pattern":  "reincarnation_cheat",
        "cheat_scale":   3,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 40,
        "reality_cost":  10,
        "cost_severity": 0,
        "style_key":     "style_comedy_speed",
        "default_target_eps": 40,
        "default_word_count": 1800,
    },
    "異世界配信者（バズり無双）": {
        "plot_pattern":  "reincarnation_cheat",
        "cheat_scale":   4,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 100,
        "reality_cost":  10,
        "cost_severity": 0,
        "style_key":     "style_chat_log",
        "default_target_eps": 50,
        "default_word_count": 2000,
    },
    "癒やしの聖女（溺愛平和）": {
        "plot_pattern":  "slow_life",
        "cheat_scale":   5,
        "growth_curve":  "徐々に成長(王道)",
        "system_assist": 50,
        "reality_cost":  20,
        "cost_severity": 0,
        "style_key":     "style_bookworm_daily",
        "default_target_eps": 35,
        "default_word_count": 1700,
    },
    "万能魔導具師（快適生活）": {
        "plot_pattern":  "slow_life",
        "cheat_scale":   3,
        "growth_curve":  "徐々に成長(王道)",
        "system_assist": 60,
        "reality_cost":  30,
        "cost_severity": 1,
        "style_key":     "style_bookworm_daily",
        "default_target_eps": 40,
        "default_word_count": 1900,
    },
    "モブ生徒の学園青春記": {
        "plot_pattern":  "slow_life",
        "cheat_scale":   1,
        "growth_curve":  "徐々に成長(王道)",
        "system_assist": 20,
        "reality_cost":  10,
        "cost_severity": 1,
        "style_key":     "style_web_standard",
        "default_target_eps": 25,
        "default_word_count": 1200,
    },
    "お気楽宝探し（浪漫追求）": {
        "plot_pattern":  "reincarnation_cheat",
        "cheat_scale":   3,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 40,
        "reality_cost":  40,
        "cost_severity": 2,
        "style_key":     "style_light_fun",
        "default_target_eps": 50,
        "default_word_count": 2300,
    },
    "聖獣カフェのまったり経営": {
        "plot_pattern":  "slow_life",
        "cheat_scale":   4,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 80,
        "reality_cost":  10,
        "cost_severity": 0,
        "style_key":     "style_bookworm_daily",
        "default_target_eps": 30,
        "default_word_count": 1400,
    },
    "ダンジョン農家（魔力で豊作）": {
        "plot_pattern":  "slow_life",
        "cheat_scale":   4,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 90,
        "reality_cost":  5,
        "cost_severity": 0,
        "style_key":     "style_bookworm_daily",
        "default_target_eps": 40,
        "default_word_count": 1700,
    },
    "癒やしの衛生兵（後方支援無双）": {
        "plot_pattern":  "exile_rise",
        "cheat_scale":   3,
        "growth_curve":  "徐々に成長(王道)",
        "system_assist": 40,
        "reality_cost":  20,
        "cost_severity": 1,
        "style_key":     "style_light_fun",
        "default_target_eps": 50,
        "default_word_count": 2400,
    },
    "異世界コンビニ（現代品無双）": {
        "plot_pattern":  "slow_life",
        "cheat_scale":   5,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 100,
        "reality_cost":  0,
        "cost_severity": 0,
        "style_key":     "style_web_standard",
        "default_target_eps": 45,
        "default_word_count": 2000,
    },
    "モブ執事の矜持（有能側近）": {
        "plot_pattern":  "reincarnation_cheat",
        "cheat_scale":   3,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 30,
        "reality_cost":  40,
        "cost_severity": 1,
        "style_key":     "style_villainess_elegant",
        "default_target_eps": 50,
        "default_word_count": 2300,
    },
    "不老不死の道楽（伝説の趣味人）": {
        "plot_pattern":  "slow_life",
        "cheat_scale":   4,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 10,
        "reality_cost":  10,
        "cost_severity": 0,
        "style_key":     "style_serious_fantasy",
        "default_target_eps": 70,
        "default_word_count": 2800,
    },
    "ギャル転生（ハイテンション）": {
        "plot_pattern":  "reincarnation_cheat",
        "cheat_scale":   3,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 60,
        "reality_cost":  10,
        "cost_severity": 0,
        "style_key":     "style_comedy_speed",
        "default_target_eps": 40,
        "default_word_count": 1700,
    },
    "辺境開拓（ホワイト領地経営）": {
        "plot_pattern":  "slow_life",
        "cheat_scale":   4,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 70,
        "reality_cost":  20,
        "cost_severity": 1,
        "style_key":     "style_bookworm_daily",
        "default_target_eps": 60,
        "default_word_count": 2500,
    },
    "竜騎士無双（伝説の再起）": {
        "plot_pattern":  "exile_rise",
        "cheat_scale":   5,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 30,
        "reality_cost":  40,
        "cost_severity": 2,
        "style_key":     "style_web_standard",
        "default_target_eps": 70,
        "default_word_count": 2900,
    },
    "鉄壁タンク（不動の守護）": {
        "plot_pattern":  "exile_rise",
        "cheat_scale":   4,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 50,
        "reality_cost":  50,
        "cost_severity": 1,
        "style_key":     "style_iron_wall",
        "default_target_eps": 65,
        "default_word_count": 2700,
    },
    "鬼人進化（弱肉強食）": {
        "plot_pattern":  "reincarnation_cheat",
        "cheat_scale":   5,
        "growth_curve":  "徐々に成長(王道)",
        "system_assist": 30,
        "reality_cost":  70,
        "cost_severity": 3,
        "style_key":     "style_evolution",
        "default_target_eps": 75,
        "default_word_count": 3000,
    },
    "禁書司書（全知の隠者）": {
        "plot_pattern":  "slow_life",
        "cheat_scale":   3,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 10,
        "reality_cost":  80,
        "cost_severity": 2,
        "style_key":     "style_forbidden_library",
        "default_target_eps": 50,
        "default_word_count": 2400,
    },
    "豪運ギャンブラー（一攫千金）": {
        "plot_pattern":  "reincarnation_cheat",
        "cheat_scale":   4,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 60,
        "reality_cost":  30,
        "cost_severity": 2,
        "style_key":     "style_high_luck_gambler",
        "default_target_eps": 55,
        "default_word_count": 2600,
    },
    "旋律の魔術師（伝説の演奏）": {
        "plot_pattern":  "slow_life",
        "cheat_scale":   3,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 40,
        "reality_cost":  20,
        "cost_severity": 1,
        "style_key":     "style_melody_mage",
        "default_target_eps": 40,
        "default_word_count": 1900,
    },
    "孤高の真祖（夜の支配者）": {
        "plot_pattern":  "reincarnation_cheat",
        "cheat_scale":   5,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 20,
        "reality_cost":  40,
        "cost_severity": 1,
        "style_key":     "style_true_ancestor",
        "default_target_eps": 60,
        "default_word_count": 2700,
    },
    "遺物修理屋（職人の矜持）": {
        "plot_pattern":  "slow_life",
        "cheat_scale":   3,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 30,
        "reality_cost":  10,
        "cost_severity": 1,
        "style_key":     "style_relic_repairer",
        "default_target_eps": 45,
        "default_word_count": 2100,
    },
    "呪いの剣聖（一刀両断）": {
        "plot_pattern":  "exile_rise",
        "cheat_scale":   4,
        "growth_curve":  "徐々に成長(王道)",
        "system_assist": 0,
        "reality_cost":  90,
        "cost_severity": 4,
        "style_key":     "style_cursed_sword",
        "default_target_eps": 70,
        "default_word_count": 2900,
    },
    "影の支配者（黒幕の愉悦）": {
        "plot_pattern":  "reincarnation_cheat",
        "cheat_scale":   3,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 40,
        "reality_cost":  50,
        "cost_severity": 2,
        "style_key":     "style_shadow_ruler",
        "default_target_eps": 60,
        "default_word_count": 2600,
    },
    "最強陰陽師（和風無双）": {
        "plot_pattern":  "reincarnation_cheat",
        "cheat_scale":   5,
        "growth_curve":  "最初からカンスト(無双)",
        "system_assist": 50,
        "reality_cost":  30,
        "cost_severity": 2,
        "style_key":     "style_onmyoji_master",
        "default_target_eps": 65,
        "default_word_count": 2800,
    },
}


COMMERCIAL_ROLE_DESCRIPTIONS = {
    "avatar_of_desire": "欲望の化身として読者の感情を揚げるキャラクター",
    "hate_magnet": "悪行で読者の敵意を集め、後のシックスでのカタルシスを準備させる",
    "status_flip_trigger": "地位の入れ替わりをトリガーとした展開をする",
    "unique_value_proposition": "ユニークな価値を持つキャラクター",
    "information_hegemony": "情報のコントロールを行う主導者",
    "unconditional_supporter": "無条件の支援者としての役割",
    "contrast_engine": "対比を通じて主人公の良さを際立たせる",
    "growth_investment": "成長と投資を示すキャラクター",
    "destined_resonance": "運命的な共鳴を描くキャラクター",
}

DEFAULT_COMMERCIAL_ROLES = ["avatar_of_desire", "growth_investment", "hate_magnet"]

ARCHETYPE_KEY_ALIASES = {
    "pure_love": "純愛官能（情緒重視）",
    "bondage": "背徳官能（心理葛藤重視）",
    "fantasy": "ファンタジー官能（異種族・魔法感覚）",
    "married": "夫婦/既婚官能（日常情緒）"
}

EASY_MODE_KEYWORDS_MAP = {
    "easy": ["初心者向け", "やさしい", "簡単"],
    "normal": ["標準", "普通"],
    "hard": ["上級者向け", "難しい", "挑戦"]
}

WIZARD_GENRE_OPTIONS = [
    "ファンタジー",
    "SF",
    "現代",
    "歴史",
    "官能/ロマンス",
    "その他"
]

WIZARD_ARCHETYPE_LABELS = {
    "純愛官能（情緒重視）": "Pure Love",
    "背徳官能（心理葛藤重視）": "Bondage",
    "ファンタジー官能（異種族・魔法感覚）": "Fantasy",
    "夫婦/既婚官能（日常情緒）": "Married"
}

EASY_GENRES = {
    "⚔️ 追放ざまぁ":    {"genre": "ファンタジー", "archetype": "overcoming_the_monster", "desc": "不当に追放された主人公が成り上がり、元の仲間を見返す爽快ストーリー"},
    "🌸 悪役令嬢":      {"genre": "恋愛",         "archetype": "rags_to_riches", "desc": "乙女ゲームに転生した令嬢が破滅フラグを回避しながら逆転を狙う"},
    "🔄 死に戻り":      {"genre": "ファンタジー", "archetype": "tragedy", "desc": "何度も死に戻りながら完璧な結末を目指す絶望と執念のループ作品"},
    "🍲 ほのぼのスローライフ": {"genre": "ファンタジー", "archetype": "rebirth", "desc": "異世界でのんびりと料理や農業を楽しむ癒し系スローライフ"},
    "🌸 純愛官能":      {"genre": "官能/ロマンス", "archetype": "pure_love_erotic", "desc": "触覚・呼吸・匂いを主軸に、情緒と余韻を重んじる純愛官能ストーリー", "nsfw_only": True},
    "💜 背徳官能":      {"genre": "官能/ロマンス", "archetype": "taboo_erotic", "desc": "タブーに挑む心理葛藤と背徳感を重視した大人向けの心理劇", "nsfw_only": True},
    "✨ 幻想官能":      {"genre": "官能/ロマンス", "archetype": "fantasy_erotic", "desc": "異種族の身体感覚と魔法を交えたファンタジー官能描写", "nsfw_only": True},
    "💑 夫婦官能":      {"genre": "官能/ロマンス", "archetype": "married_erotic", "desc": "長年連れ添った夫婦の親密性の深化と日常の情緒", "nsfw_only": True},
}

def resolve_archetype_key(key):
    """Resolve archetype key to canonical form."""
    return ARCHETYPE_KEY_ALIASES.get(key, key)
