from typing import Any, List, Protocol, Tuple


class IDatabaseConnection(Protocol):
    def execute(self, sql: Any, params: Tuple = ()) -> Any: ...
    def fetchone(self) -> Any: ...
    def fetchall(self) -> List[Any]: ...
    def rollback(self) -> None: ...
    def commit(self) -> None: ...
    def close(self) -> None: ...

