from typing import Any, Protocol


class IDatabaseConnection(Protocol):
    def execute(self, sql: Any, params: tuple = ()) -> Any: ...
    def fetchone(self) -> Any: ...
    def fetchall(self) -> list[Any]: ...
    def rollback(self) -> None: ...
    def commit(self) -> None: ...
    def close(self) -> None: ...
