#!/usr/bin/env python3
"""
Create a manifest file mapping asset types to generated image paths.
Scans the static/generated-ui-assets/ directory and outputs a TypeScript manifest.
"""
import json
import os
from pathlib import Path

# Directory where generated images are stored
GENERATED_DIR = Path(__file__).parent.parent / "static" / "generated-ui-assets"
# Output TypeScript manifest file in the frontend src/lib directory
OUTPUT_TS = Path(__file__).parent.parent / "frontend" / "src" / "lib" / "uiAssetManifest.ts"
# Optional JSON manifest for debugging
OUTPUT_JSON = Path(__file__).parent.parent / "static" / "generated-ui-assets" / "manifest.json"

def main():
    if not GENERATED_DIR.is_dir():
        print(f"Generated directory not found: {GENERATED_DIR}")
        return

    # Scan for image files (we'll assume .png for simplicity)
    image_files = list(GENERATED_DIR.glob("*.png"))
    if not image_files:
        print(f"No image files found in {GENERATED_DIR}")
        return

    # Group by assetType (part before first underscore)
    grouped = {}
    for f in image_files:
        # filename without extension
        name = f.stem
        # Split on first underscore
        if '_' in name:
            asset_type = name.split('_')[0]
        else:
            asset_type = name  # fallback
        grouped.setdefault(asset_type, []).append(f)

    # For each assetType, pick the most recently modified file
    manifest = {}
    for asset_type, files in grouped.items():
        latest_file = max(files, key=lambda p: p.stat().st_mtime)
        # Path relative to the static folder (since we serve from /static)
        # We want the URL to be: /static/generated-ui-assets/filename.png
        rel_path = f"generated-ui-assets/{latest_file.name}"
        manifest[asset_type] = f"/{rel_path}"  # leading slash for root-relative path

    # Write TypeScript manifest
    OUTPUT_TS.parent.mkdir(parents=True, exist_ok=True)
    ts_content = f"""// Auto-generated by scripts/create-manifest.py
// Do not edit manually.
export const uiAssetManifest: {{ [key: string]: string }} = {json.dumps(manifest, indent=2)};
"""
    OUTPUT_TS.write_text(ts_content, encoding="utf-8")
    print(f"Generated TypeScript manifest at {OUTPUT_TS}")

    # Write JSON manifest for reference
    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_JSON.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"Generated JSON manifest at {OUTPUT_JSON}")

if __name__ == "__main__":
    main()