"""
src/agents/erotic_integrity.py
官能・シーン整合性チェックのエージェント (後方互換性用ファサード)。
実体は src.agents.erotic パッケージに分割・配置されています。
"""

from __future__ import annotations

from src.agents.erotic import (
    COMBAT_KEYWORDS,
    CONSENT_ALL_CHARACTERS_KEYWORDS,
    CONSENT_CONTINUATION_KEYWORDS,
    CONSENT_EXPLICIT_KEYWORDS,
    CONSENT_IMPLICIT_KEYWORDS,
    CONSENT_REFUSAL_KEYWORDS,
    CONVERSATION_KEYWORDS,
    EXPLICIT_CONSENT_KEYWORDS,
    EXPLORATION_KEYWORDS,
    FORESHADOW_KEYWORDS,
    IMPLICIT_CONSENT_KEYWORDS,
    ITEM_KEYWORDS,
    MONOLOGUE_KEYWORDS,
    MUTUAL_CONSENT_KEYWORDS,
    REFUSAL_KEYWORDS,
    REST_KEYWORDS,
    SCENE_TYPES,
    SIMPLE_MUTUAL_CONSENT_KEYWORDS,
    TIME_KEYWORDS,
    TRAVEL_KEYWORDS,
    CharacterStateSnapshot,
    ContinuityReport,
    ContinuityTracker,
    EroticCurve,
    EroticIntegrityChecker,
    EroticPoint,
    EroticQualityReport,
    EroticQualityScorer,
    SceneContinuityTracker,
    SceneStateSnapshot,
    SceneTypeDetector,
)

__all__ = [
    "SCENE_TYPES",
    "COMBAT_KEYWORDS",
    "CONVERSATION_KEYWORDS",
    "EXPLORATION_KEYWORDS",
    "TRAVEL_KEYWORDS",
    "REST_KEYWORDS",
    "MONOLOGUE_KEYWORDS",
    "FORESHADOW_KEYWORDS",
    "TIME_KEYWORDS",
    "ITEM_KEYWORDS",
    "EXPLICIT_CONSENT_KEYWORDS",
    "IMPLICIT_CONSENT_KEYWORDS",
    "REFUSAL_KEYWORDS",
    "MUTUAL_CONSENT_KEYWORDS",
    "SIMPLE_MUTUAL_CONSENT_KEYWORDS",
    "CONSENT_EXPLICIT_KEYWORDS",
    "CONSENT_IMPLICIT_KEYWORDS",
    "CONSENT_REFUSAL_KEYWORDS",
    "CONSENT_ALL_CHARACTERS_KEYWORDS",
    "CONSENT_CONTINUATION_KEYWORDS",
    "EroticCurve",
    "EroticPoint",
    "EroticQualityReport",
    "EroticQualityScorer",
    "SceneStateSnapshot",
    "SceneContinuityTracker",
    "CharacterStateSnapshot",
    "ContinuityReport",
    "ContinuityTracker",
    "EroticIntegrityChecker",
    "SceneTypeDetector",
]
