"""Initial schema

Revision ID: 262b595ebb00
Revises: 
Create Date: 2026-06-04 23:37:24.798467

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '262b595ebb00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('concept', sa.String(), nullable=True),
    sa.Column('synopsis', sa.String(), nullable=True),
    sa.Column('target_eps', sa.Integer(), nullable=True),
    sa.Column('style_dna', sa.Text(), nullable=True),
    sa.Column('marketing_data', sa.Text(), nullable=True),
    sa.Column('cumulative_stress', sa.Integer(), nullable=True),
    sa.Column('cumulative_qol', sa.Integer(), nullable=True),
    sa.Column('cumulative_cost', sa.Float(), nullable=True),
    sa.Column('sanctuary_integrity', sa.Integer(), nullable=True),
    sa.Column('current_branch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_styles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('internal_state',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_key', sa.String(), nullable=True),
    sa.Column('version_tag', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('ab_test_metrics', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style_fragments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bible',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('revealed', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('fork_ep_num', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapters',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('ep_num', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('score_story', sa.Integer(), nullable=True),
    sa.Column('killer_phrase', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('world_state', sa.Text(), nullable=True),
    sa.Column('trinity_review_log', sa.Text(), nullable=True),
    sa.Column('ai_insight', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('stress_delta', sa.Integer(), nullable=True),
    sa.Column('qol_delta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('branch_id', 'ep_num')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('registry_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('report_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_patches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('patch_type', sa.String(), nullable=True),
    sa.Column('patch_content', sa.Text(), nullable=True),
    sa.Column('ab_test_result', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plot',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('ep_num', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('thought_process', sa.Text(), nullable=True),
    sa.Column('detailed_blueprint', sa.Text(), nullable=True),
    sa.Column('tension', sa.Integer(), nullable=True),
    sa.Column('stress', sa.Integer(), nullable=True),
    sa.Column('catharsis', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('scenes', sa.Text(), nullable=True),
    sa.Column('is_catharsis', sa.Boolean(), nullable=True),
    sa.Column('catharsis_type', sa.String(), nullable=True),
    sa.Column('love_meter', sa.Integer(), nullable=True),
    sa.Column('next_hook', sa.Text(), nullable=True),
    sa.Column('misunderstanding_gap', sa.Text(), nullable=True),
    sa.Column('lite_model_director_notes', sa.Text(), nullable=True),
    sa.Column('current_chain_phase', sa.String(), nullable=True),
    sa.Column('script_content', sa.Text(), nullable=True),
    sa.Column('resolution_style', sa.String(), nullable=True),
    sa.Column('burned_cost_or_loot', sa.String(), nullable=True),
    sa.Column('antagonist_status', sa.String(), nullable=True),
    sa.Column('thematic_milestone', sa.String(), nullable=True),
    sa.Column('state_integrity_score', sa.Integer(), nullable=True),
    sa.Column('healed_fields', sa.Text(), nullable=True),
    sa.Column('is_micro_catharsis', sa.Boolean(), nullable=True),
    sa.Column('information_asymmetry_level', sa.Float(), nullable=True),
    sa.Column('cost_score', sa.Float(), nullable=True),
    sa.Column('qol_delta', sa.Integer(), nullable=True),
    sa.Column('discovery_item', sa.Text(), nullable=True),
    sa.Column('sanctuary_event', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('branch_id', 'ep_num')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plot')
    op.drop_table('pending_patches')
    op.drop_table('optimization_history')
    op.drop_table('characters')
    op.drop_table('chapters')
    op.drop_table('branches')
    op.drop_table('bible')
    op.drop_table('style_fragments')
    op.drop_table('prompt_versions')
    op.drop_table('internal_state')
    op.drop_table('custom_styles')
    op.drop_table('books')
    # ### end Alembic commands ###

