"""prompt_usage_metrics_table

Revision ID: a1b2c3d4e5f6
Revises: 1779cff3e20d
Create Date: 2026-07-07 10:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[Sequence[str], str, None] = '1779cff3e20d'
branch_labels: Union[Sequence[str], str, None] = None
depends_on: Union[Sequence[str], str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'prompt_usage_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('template_name', sa.String(length=255), nullable=False),
        sa.Column('hits', sa.Integer(), nullable=False),
        sa.Column('total_time_ms', sa.Float(), nullable=False),
        sa.Column('avg_time_ms', sa.Float(), nullable=False),
        sa.Column('last_accessed', sa.DateTime(), nullable=False),
        sa.Column('error_count', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # Create index for faster querying by template and time
    op.create_index('idx_prompt_usage_template_time', 'prompt_usage_log', ['template_name', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prompt_usage_template_time', table_name='prompt_usage_log')
    op.drop_table('prompt_usage_log')
    # ### end Alembic commands ###