"""Add multi-dimensional tension fields

Revision ID: c2d671bd984b
Revises: 1779cff3e20d
Create Date: 2026-06-20 15:51:37.246873

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c2d671bd984b'
down_revision: Union[str, Sequence[str], None] = '1779cff3e20d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_table('uow_test')
    except Exception:
        pass
    op.add_column('books', sa.Column('cumulative_physical_tension', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('cumulative_psychological_tension', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('cumulative_social_tension', sa.Integer(), nullable=True))
    op.add_column('plot', sa.Column('physical_tension_delta', sa.Integer(), nullable=True))
    op.add_column('plot', sa.Column('psychological_tension_delta', sa.Integer(), nullable=True))
    op.add_column('plot', sa.Column('social_tension_delta', sa.Integer(), nullable=True))
    try:
        op.drop_column('plot', 'is_plot_twist')
    except Exception:
        pass
    try:
        op.alter_column('prompt_versions', 'id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
    except Exception:
        pass
    try:
        op.drop_constraint(None, 'prompt_versions', type_='foreignkey')
        op.create_foreign_key(None, 'prompt_versions', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prompt_versions', type_='foreignkey')
    op.create_foreign_key(None, 'prompt_versions', 'books', ['book_id'], ['id'])
    op.alter_column('prompt_versions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('plot', sa.Column('is_plot_twist', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
    op.drop_column('plot', 'social_tension_delta')
    op.drop_column('plot', 'psychological_tension_delta')
    op.drop_column('plot', 'physical_tension_delta')
    op.drop_column('books', 'cumulative_social_tension')
    op.drop_column('books', 'cumulative_psychological_tension')
    op.drop_column('books', 'cumulative_physical_tension')
    op.create_table('uow_test',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('val', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

