"""Add audit_issues table

Revision ID: c916c38a8e17
Revises: 7bdaed90ce8b
Create Date: 2026-06-12 11:15:20.047113

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c916c38a8e17'
down_revision: Union[str, Sequence[str], None] = '7bdaed90ce8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('audit_issues',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('book_id', sa.Integer(), nullable=True),
        sa.Column('ep_num', sa.Integer(), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('severity', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('evidence_past', sa.Text(), nullable=True),
        sa.Column('evidence_current', sa.Text(), nullable=True),
        sa.Column('constraint_for_next_ep', sa.Text(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('resolved_note', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    except Exception as e:
        print(f"Skipping create_table audit_issues: {e}")
    try:
        op.drop_table('uow_test')
    except Exception as e:
        print(f"Skipping drop_table uow_test: {e}")
    try:
        op.drop_column('books', 'cumulative_stress')
    except Exception as e:
        print(f"Skipping drop_column cumulative_stress: {e}")
    try:
        op.drop_index(op.f('ix_outbox_status'), table_name='outbox')
    except Exception as e:
        print(f"Skipping drop_index ix_outbox_status: {e}")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_outbox_status'), 'outbox', ['status'], unique=False)
    op.add_column('books', sa.Column('cumulative_stress', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.create_table('uow_test',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('val', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('audit_issues')
    # ### end Alembic commands ###

