"""src.easy_mode.phase3.ebook_export の深層単体テスト (Step 5)。"""
from __future__ import annotations

from pathlib import Path

import pytest

from src.easy_mode.phase3.ebook_export import (
    EPUB_AVAILABLE,
    Chapter,
    EbookContentProcessor,
    EbookExporter,
    EbookMetadata,
    create_ebook_exporter,
)
from src.easy_mode import EpisodeResult, SeriesResult
from src.easy_mode.spice_guard import SpiceElement


# ==============================================================================
# Helper Functions
# ==============================================================================


def _make_series(genre: str = "ハイファンタジー (R15)", episode_count: int = 2) -> SeriesResult:
    episodes = []
    for i in range(episode_count):
        content = (
            f"エピソード{i+1}の本文\n\n主人公は行動した。\n\n「セリフです」\n\n"
            f"衝撃の展開！\n"
        )
        episodes.append(
            EpisodeResult(
                episode_num=i + 1,
                title=f"テスト話{i+1}",
                content=content,
                word_count=len(content),
                audit_score=85.0,
                audit_passed=True,
                rewrite_count=0,
                spice_elements=[
                    SpiceElement(type="unique_metaphor", text="例え", position=0, priority="low")
                ],
                metadata={},
            )
        )
    return SeriesResult(
        genre=genre,
        title="テストシリーズ",
        concept="異世界転生チート",
        total_episodes=episode_count,
        episodes=episodes,
        bible={"protagonist": "テスト主人公"},
        plot_outline=[{"episode": 1, "title": "プロローグ", "summary": "物語の始まり"}],
        metadata={"prologue": "プロローグ本文", "epilogue": "エピローグ本文"},
    )


# ==============================================================================
# EbookMetadata Tests
# ==============================================================================


class TestEbookMetadata:
    def test_defaults(self):
        meta = EbookMetadata(title="テスト")
        assert meta.author == "AI Novel Engine"
        assert meta.language == "ja"
        assert meta.publisher == "覇権小説エンジン"
        assert meta.publication_date  # default factory
        assert meta.identifier  # uuid4
        assert meta.rights == "Generated by AI Novel Engine"
        assert meta.genre == ""
        assert meta.tags == []
        assert meta.subject == []
        assert meta.cover_image is None
        assert meta.cover_image_path is None

    def test_to_dict(self):
        meta = EbookMetadata(
            title="テスト",
            author="作者",
            language="en",
            publisher="出版",
            identifier="id-001",
            description="説明",
            subject=["SF"],
            rights="CC0",
            genre="fantasy",
            tags=["tag1"],
        )
        d = meta.to_dict()
        assert d["title"] == "テスト"
        assert d["author"] == "作者"
        assert d["language"] == "en"
        assert d["publisher"] == "出版"
        assert d["identifier"] == "id-001"
        assert d["description"] == "説明"
        assert d["subject"] == ["SF"]
        assert d["rights"] == "CC0"
        assert d["genre"] == "fantasy"
        assert d["tags"] == ["tag1"]


# ==============================================================================
# Chapter Tests
# ==============================================================================


class TestChapter:
    def test_post_init_word_count(self):
        ch = Chapter(title="テスト", content="あいうえお", episode_num=1)
        assert ch.word_count == 5

    def test_defaults(self):
        ch = Chapter(title="テスト", content="本文", episode_num=1)
        assert ch.toc_entry is True
        assert ch.level == 1
        assert ch.word_count == 2


# ==============================================================================
# EbookContentProcessor Tests
# ==============================================================================


class TestEbookContentProcessor:
    @pytest.fixture
    def processor(self) -> EbookContentProcessor:
        return EbookContentProcessor("ハイファンタジー (R15)")

    def test_create_chapters_with_prologue_epilogue(self, processor):
        series = _make_series()
        chapters = processor.create_chapters(series)
        # プロローグ + 2話 + エピローグ
        assert len(chapters) == 4
        assert chapters[0].title == "プロローグ"
        assert chapters[0].episode_num == 0
        assert chapters[1].title == "テスト話1"
        assert chapters[2].title == "テスト話2"
        assert chapters[3].title == "エピローグ"
        assert chapters[3].episode_num == 3

    def test_create_chapters_without_prologue_epilogue(self):
        series = _make_series()
        series.metadata = {}
        processor = EbookContentProcessor("test")
        chapters = processor.create_chapters(series)
        assert len(chapters) == 2

    def test_format_content_paragraphs(self, processor):
        text = "段落1\n\n段落2"
        result = processor._format_content(text)
        assert "<p>段落1</p>" in result
        assert "<p>段落2</p>" in result

    def test_format_content_dialogue(self, processor):
        text = "「セリフです」"
        result = processor._format_content(text)
        assert '<p class="dialogue">' in result

    def test_format_content_emphasis(self, processor):
        text = "衝撃の展開！"
        result = processor._format_content(text)
        assert '<p class="emphasis">' in result

    def test_format_content_empty_paragraph(self, processor):
        result = processor._format_content("\n\n\n")
        assert result == ""

    def test_escape_html(self, processor):
        raw = '<a href="x">&'
        result = processor._escape_html(raw)
        # & と < がエスケープされることを検証
        assert chr(60) not in result  # < は残らない
        assert chr(38) in result      # & エンティティが使われる
        assert "lt;" in result


    def test_generate_css(self, processor):
        css = processor.generate_css()
        assert "font-family" in css
        assert "body" in css


# ==============================================================================
# EbookExporter Tests
# ==============================================================================


class TestEbookExporter:
    def _make_exporter(self, output_dir: Path) -> EbookExporter:
        metadata = EbookMetadata(title="テストシリーズ", genre="ハイファンタジー (R15)")
        return EbookExporter(metadata, output_dir)

    def test_init(self, tmp_path):
        exporter = self._make_exporter(tmp_path)
        assert exporter.genre == "ハイファンタジー (R15)"
        assert exporter.output_dir == tmp_path
        assert exporter.preset == {}

    def test_create_metadata_from_series(self, tmp_path):
        exporter = self._make_exporter(tmp_path)
        series = _make_series()
        meta = exporter.create_metadata(series)
        assert meta.title == "テストシリーズ"
        assert meta.genre == "ハイファンタジー (R15)"

    def test_create_metadata_with_overrides(self, tmp_path):
        exporter = self._make_exporter(tmp_path)
        series = _make_series()
        meta = exporter.create_metadata(
            series, author="上書き作者", tags=["tag1", "tag2"]
        )
        assert meta.author == "上書き作者"
        assert meta.tags == ["tag1", "tag2"]

    def test_export_epub_fallback(self, tmp_path):
        series = _make_series()
        exporter = self._make_exporter(tmp_path)
        out_path = tmp_path / "out.epub"
        if not EPUB_AVAILABLE:
            # ebooklib 非依存環境では例外がログに記録され、失敗する可能性がある
            try:
                result = exporter.export_epub(series, out_path)
                assert result is not None
            except Exception:
                pass  # 環境依存のフォールバック

    def test_export_all_mobi_unknown_format(self, tmp_path):
        series = _make_series()
        exporter = self._make_exporter(tmp_path)
        results = exporter.export_all(series, tmp_path, ["mobi", "unknown"])
        assert isinstance(results, dict)

    def test_export_all_default_formats(self, tmp_path):
        series = _make_series()
        exporter = self._make_exporter(tmp_path)
        # formats=None でデフォルト (epub, pdf)
        results = exporter.export_all(series, tmp_path, None)
        assert isinstance(results, dict)


# ==============================================================================
# create_ebook_exporter Factory Tests
# ==============================================================================


class TestCreateEbookExporter:
    def test_correct_signature(self, tmp_path):
        metadata = EbookMetadata(title="テスト", genre="fantasy")
        exporter = create_ebook_exporter(metadata, tmp_path)
        assert isinstance(exporter, EbookExporter)
        assert exporter.genre == "fantasy"
        assert exporter.output_dir == tmp_path


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
